# Generated by Django 3.2 on 2021-04-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_createtodolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
